[book]
authors = ["IgorP"]
language = "en"
multilingual = false
src = "src"
title = "JSXGraph Book"

[build]
build-dir = "docs"

[output.html]
additional-css = ["files/jsxgraph.css"]
additional-js = ["files/jsxgraphcore.js"]
mathjax-support = true