[book]
authors = ["IgorP"]
language = "en"
multilingual = false
src = "src"
title = "{lang=EN}JSXGraph Book{/lang}{lang=SI}Knjiga o JSXGraphu{/lang}{lang=CZ}Příručka JSXGraph{/lang}{lang=DE}JSXGraph-Buch{/lang}"

[build]
build-dir = "docs"

[output.html]
theme = "src/theme"
mathjax-support = true